"""
This module performs hand-engineered classical feature extraction and deep learning embedding extraction on images.
It computes a 590-dimensional feature vector consisting of 14 classical computer vision features (capturing
frequency, color gamut, micro-textures, glare, and bezel geometry) concatenated with 576-dimensional frozen 
embeddings from a MobileNetV3-Small architecture. The pretrained MobileNet model is initialized once and cached
as a module-level global variable on the first import to minimize instantiation overhead during inference.
"""

import os
import sys
import cv2
import numpy as np
from PIL import Image
from skimage.feature import local_binary_pattern

import torch
import torchvision.models as tv_models
from torchvision.models import MobileNet_V3_Small_Weights

# Global cache for the MobileNetV3-Small model to avoid reloading weights across inference calls
_MOBILENET_MODEL = None

# FEATURE_NAMES defines the human-readable labels corresponding to each element in the feature vector.
# It is parallel to the array returned by extract_features() and is used by train.py for logging and interpretability.
FEATURE_NAMES = [
    "freq_peak_to_average",
    "freq_high_to_low_energy_ratio",
    "color_saturation_mean",
    "color_saturation_std",
    "color_clipped_pixel_ratio",
    "color_l_dynamic_range",
    "color_cast_a",
    "color_cast_b",
    "texture_laplacian_var",
    "texture_lbp_entropy",
    "glare_blob_count",
    "glare_avg_hardness",
    "geom_aligned_line_count",
    "geom_avg_line_len_rel"
] + [f"mobilenet_emb_{i:03d}" for i in range(576)]


def _extract_frequency_features(gray: np.ndarray) -> tuple[float, float]:
    """
    Measures periodic artifacts in the frequency domain. Moiré grid patterns generated by pixel-grid sampling 
    interference create high-energy spectral peaks at high frequencies, which are absent in natural images following 
    a smooth 1/f spectral power decay. This helper computes the 2D Fast Fourier Transform (FFT) magnitude spectrum 
    and returns the peak-to-average ratio in the high-frequency band, alongside the high-to-low frequency energy ratio.
    """
    # Resize to a fixed size for consistent frequency resolution across varying input resolutions
    gray_512 = cv2.resize(gray, (512, 512), interpolation=cv2.INTER_AREA)
    
    # Compute 2D FFT and shift the zero-frequency component to the center
    f = np.fft.fft2(gray_512)
    fshift = np.fft.fftshift(f)
    magnitude_spectrum = np.abs(fshift)
    
    # Generate coordinates and distances from center (256, 256)
    y, x = np.ogrid[:512, :512]
    r = np.sqrt((y - 256)**2 + (x - 256)**2) # 256 is the DC center frequency offset for 512x512
    
    # Masks for low-frequency annulus (excluding DC spike at 0) and high-frequency annulus
    low_mask = (r >= 5) & (r < 50)           # r >= 5 ignores the central DC spike; r < 50 covers low-frequency bands
    high_mask = (r >= 60) & (r < 250)         # r >= 60 targets potential moire peaks; r < 250 ignores border boundary artifacts
    
    high_mag = magnitude_spectrum[high_mask]
    low_mag = magnitude_spectrum[low_mask]
    
    if len(high_mag) == 0 or len(low_mag) == 0:
        return 0.0, 0.0
        
    mean_high = np.mean(high_mag)
    peak_to_average = np.max(high_mag) / (mean_high + 1e-8)
    
    high_to_low_energy = np.sum(high_mag) / (np.sum(low_mag) + 1e-8)
    
    return float(peak_to_average), float(high_to_low_energy)


def _extract_color_features(img_bgr: np.ndarray) -> tuple[float, float, float, float, float, float]:
    """
    Measures color gamut distribution and color casting profiles. LCD/LED screens and paper printouts exhibit 
    significantly compressed dynamic ranges and saturation spreads compared to natural scenes, along with distinct 
    chromaticity biases (color casts) due to display backlights or print ink mixtures. This helper converts 
    images to HSV and CIELAB color spaces, returning saturation mean and standard deviation, luminance clipping 
    ratios, percentile-clipped dynamic range, and average chromaticity deviations (a and b color cast metrics).
    """
    img_hsv = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2HSV)
    img_lab = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2Lab)
    
    S = img_hsv[:, :, 1]
    L = img_lab[:, :, 0]
    a = img_lab[:, :, 1]
    b = img_lab[:, :, 2]
    
    # Saturation statistics
    sat_mean = float(np.mean(S))
    sat_std = float(np.std(S))
    
    # Clipping statistics (luminance < 5 or > 250 on a standard 8-bit scale indicates clipped blacks/whites)
    clipped_ratio = float(np.mean((L < 5) | (L > 250)))
    
    # Dynamic range with percentile clipping (99th - 1st) to ignore isolated hot/dead pixels and sensor noise
    l_min_pct = np.percentile(L, 1)
    l_max_pct = np.percentile(L, 99)
    l_dynamic_range = float(l_max_pct - l_min_pct)
    
    # White point color cast (deviation of a and b chromaticity channels from neutral gray value 128.0)
    cast_a = float(np.mean(a) - 128.0)
    cast_b = float(np.mean(b) - 128.0)
    
    return sat_mean, sat_std, clipped_ratio, l_dynamic_range, cast_a, cast_b


def _extract_texture_features(gray: np.ndarray) -> tuple[float, float]:
    """
    Measures micro-texture density and spatial resolution sharpness. Real photos of three-dimensional scenes 
    have complex focus structures and high-variance edge frequencies, whereas recaptured displays are limited by 
    screen-panel resolution limits, pixel pitch, or printing halftone dots, creating artificial spatial regularity 
    and lower overall micro-texture entropy. This helper computes the Laplacian variance (an edge-sharpness proxy) 
    and the Shannon entropy of uniform Local Binary Patterns (LBP) representing micro-texture variations.
    """
    h, w = gray.shape
    max_dim = 1024 # 16x speedup vs full-res with negligible texture signal loss
    if max(h, w) > max_dim:
        scale = max_dim / float(max(h, w))
        gray_resized = cv2.resize(gray, (int(w * scale), int(h * scale)), interpolation=cv2.INTER_AREA)
    else:
        gray_resized = gray.copy()

    # Laplacian variance as a proxy for sharpness
    lap_var = float(cv2.Laplacian(gray_resized, cv2.CV_64F).var())
    
    # Local Binary Pattern (LBP) entropy for regular micro-textures (using P=8 neighbors and radius R=1)
    lbp = local_binary_pattern(gray_resized, P=8, R=1, method='uniform')
    
    # Uniform LBP with P=8 produces at most 10 distinct bin categories representing transitions
    n_bins = 10
    hist, _ = np.histogram(lbp.ravel(), bins=n_bins, range=(0, n_bins), density=True)
    
    # Shannon entropy
    hist = hist[hist > 0]
    lbp_entropy = float(-np.sum(hist * np.log2(hist)))
    
    return lap_var, lbp_entropy


def _extract_glare_features(gray: np.ndarray) -> tuple[float, float]:
    """
    Measures specular glare reflections. Emissive display screens (glass covers) produce sharp, high-intensity, 
    highly concentrated specular glare spots when photographed, while natural scenes feature soft, diffuse reflections 
    or highlights with gradual gradients. This helper isolates high-intensity highlights, filters candidate glare 
    blobs by area, and computes the count of glare blobs along with the average edge sharpness (hardness gradient) 
    measured along the dilated boundary ring.
    """
    # Threshold for extremely bright regions (pixel value > 240 isolates hot specular glare spots)
    bright_mask = (gray > 240).astype(np.uint8)
    
    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(bright_mask)
    
    # Sobel gradient magnitude to measure hardness/edge sharpness of the highlights
    grad_x = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3) # 3x3 Sobel kernel for edge estimation
    grad_y = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=3)
    grad_mag = np.sqrt(grad_x**2 + grad_y**2)
    
    valid_count = 0
    hardness_vals = []
    
    for i in range(1, num_labels):
        area = stats[i, cv2.CC_STAT_AREA]
        # Filter for typical size of small specular reflections (4 to 1000 pixels limits noise/large light sources)
        if 4 <= area <= 1000:
            left = stats[i, cv2.CC_STAT_LEFT]
            top = stats[i, cv2.CC_STAT_TOP]
            w_b = stats[i, cv2.CC_STAT_WIDTH]
            h_b = stats[i, cv2.CC_STAT_HEIGHT]
            
            # Crop region with 1 pixel padding for dilation boundary calculation
            r_top = max(0, top - 1)
            r_bottom = min(gray.shape[0], top + h_b + 1)
            r_left = max(0, left - 1)
            r_right = min(gray.shape[1], left + w_b + 1)
            
            cropped_labels = labels[r_top:r_bottom, r_left:r_right]
            cropped_grad = grad_mag[r_top:r_bottom, r_left:r_right]
            
            blob_mask = (cropped_labels == i).astype(np.uint8)
            # Dilate mask by 3x3 kernel and subtract original to isolate the boundary ring
            dilated = cv2.dilate(blob_mask, np.ones((3, 3), np.uint8))
            boundary = dilated - blob_mask
            
            if np.any(boundary > 0):
                # Hardness is the average gradient magnitude along the boundary interface
                hardness = float(np.mean(cropped_grad[boundary > 0]))
                hardness_vals.append(hardness)
                valid_count += 1
                
    avg_hardness = float(np.mean(hardness_vals)) if valid_count > 0 else 0.0
    
    return float(valid_count), avg_hardness


def _extract_edge_features(gray: np.ndarray) -> tuple[float, float]:
    """
    Measures linear geometric bezel alignments. Screen recaptures and paper printouts frequently feature 
    distinct straight borders, bezel frames, or page boundaries that align closely with the horizontal and vertical 
    axes of the camera, which is rare for natural objects. This helper detects straight lines using Canny edge 
    filtering and the Probabilistic Hough Line Transform, returning the count of axis-aligned lines and their 
    average length relative to the image diagonal.
    """
    h, w = gray.shape
    max_dim = 1000 # resized dimension to accelerate Hough transform calculation without losing border lines
    if max(h, w) > max_dim:
        scale = max_dim / float(max(h, w))
        new_w = int(w * scale)
        new_h = int(h * scale)
        gray_resized = cv2.resize(gray, (new_w, new_h), interpolation=cv2.INTER_AREA)
    else:
        gray_resized = gray.copy()
        
    h_r, w_r = gray_resized.shape
    diag = np.sqrt(h_r**2 + w_r**2)
    
    # Run Canny edge detector (Canny thresholds 50 and 150 cover standard edge detection ranges)
    edges = cv2.Canny(gray_resized, 50, 150)
    
    # Use optimized parameters for detecting long straight lines
    # minLineLength set to 8% of diagonal (empirically tuned on high-res phone photos; absolute pixel thresholds failed across resolutions)
    min_line_len = int(0.08 * diag)
    
    lines = cv2.HoughLinesP(edges, rho=1, theta=np.pi/180, threshold=40, 
                            minLineLength=min_line_len, maxLineGap=10) # maxLineGap=10 bridges minor bezel gaps
    
    aligned_count = 0
    len_ratios = []
    
    if lines is not None:
        for line in lines:
            x1, y1, x2, y2 = line[0]
            dx = x2 - x1
            dy = y2 - y1
            length = np.sqrt(dx**2 + dy**2)
            if length < 1e-8:
                continue
            
            # Map line angle in degrees to [0, 90]
            angle = np.abs(np.arctan2(dy, dx) * 180.0 / np.pi) % 90.0
            
            # Axis-aligned if close to horizontal (< 5 deg) or vertical (> 85 deg) within a 5-degree tolerance
            if angle < 5.0 or angle > 85.0:
                aligned_count += 1
                len_ratios.append(length / diag)
                
    avg_len_ratio = float(np.mean(len_ratios)) if aligned_count > 0 else 0.0
    
    return float(aligned_count), avg_len_ratio


def _extract_mobilenet_embedding(img_rgb: np.ndarray) -> np.ndarray:
    """
    Extracts high-level deep representations using a frozen pretrained MobileNetV3-Small architecture.
    Because recaptured photos feature distinct combinations of light reflection, panel distortions, and printout
    dullness, pretrained ImageNet weights offer a robust, dense semantic context that complements hand-engineered 
    classical cues. The image is resized to 224x224, normalized to ImageNet properties, and run through the 
    feature extraction layers, returning a 576-dimensional global average-pooled embedding.
    """
    global _MOBILENET_MODEL
    if _MOBILENET_MODEL is None:
        # Load weights once (~10MB) and freeze them on CPU
        weights = MobileNet_V3_Small_Weights.IMAGENET1K_V1
        model = tv_models.mobilenet_v3_small(weights=weights)
        model.eval()
        model.to("cpu")
        _MOBILENET_MODEL = model
        
    # Preprocess image correctly for MobileNetV3-Small
    # Resize to 224x224 (standard input dimension for ImageNet networks)
    img_resized = cv2.resize(img_rgb, (224, 224), interpolation=cv2.INTER_AREA)
    # Convert to float32 and scale to [0.0, 1.0]
    img_float = img_resized.astype(np.float32) / 255.0
    # Normalize with standard ImageNet mean and std
    mean = np.array([0.485, 0.456, 0.406], dtype=np.float32)
    std = np.array([0.229, 0.224, 0.225], dtype=np.float32)
    img_normalized = (img_float - mean) / std
    # Reorder channels from HWC to CHW format expected by PyTorch
    img_chw = np.transpose(img_normalized, (2, 0, 1))
    
    # Convert to tensor and add batch dimension (1, 3, 224, 224)
    tensor = torch.from_numpy(img_chw).unsqueeze(0)
    
    with torch.no_grad():
        # Pass through the features and avgpool layers to extract the 576 channels
        features = _MOBILENET_MODEL.features(tensor)
        features = _MOBILENET_MODEL.avgpool(features)
        features = torch.flatten(features, 1)
        embedding = features.squeeze(0).cpu().numpy()
        
    return embedding


def extract_features(image_path: str) -> np.ndarray:
    """
    Loads an image from image_path, processes it using classical feature extraction
    and MobileNetV3-Small embeddings, and returns a 590-dimensional feature vector.
    
    Raises a ValueError if the image is unreadable or corrupt.
    """
    if not os.path.exists(image_path):
        raise ValueError(f"Image path does not exist: '{image_path}'")
        
    try:
        # Load image via PIL to support a wide range of formats robustly
        with Image.open(image_path) as pil_img:
            if pil_img.mode != "RGB":
                pil_img = pil_img.convert("RGB")
            img_rgb = np.array(pil_img)
            
        img_bgr = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2BGR)
        gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
    except Exception as e:
        raise ValueError(f"Corrupt or unreadable image at '{image_path}': {str(e)}")
        
    # 1. Extract classical features (14-dim)
    f_freq1, f_freq2 = _extract_frequency_features(gray)
    f_col1, f_col2, f_col3, f_col4, f_col5, f_col6 = _extract_color_features(img_bgr)
    f_tex1, f_tex2 = _extract_texture_features(gray)
    f_glare1, f_glare2 = _extract_glare_features(gray)
    f_edge1, f_edge2 = _extract_edge_features(gray)
    
    classical_features = np.array([
        f_freq1, f_freq2,
        f_col1, f_col2, f_col3, f_col4, f_col5, f_col6,
        f_tex1, f_tex2,
        f_glare1, f_glare2,
        f_edge1, f_edge2
    ], dtype=np.float32)
    
    # 2. Extract MobileNetV3 embeddings (576-dim)
    mobilenet_features = _extract_mobilenet_embedding(img_rgb)
    
    # 3. Concatenate into a hybrid 590-dim feature vector
    features = np.concatenate([classical_features, mobilenet_features])
    
    return features


# --- Debug entrypoint: python src/features.py <image_path> ---
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python src/features.py <path_to_image>")
        sys.exit(1)
        
    img_path = sys.argv[1]
    print(f"Extracting features from: {img_path}")
    try:
        feats = extract_features(img_path)
        print("\nExtracted Features:")
        print("-" * 50)
        print(f"{'Feature Name':<30} | {'Value':<15}")
        print("-" * 50)
        
        # Print classical features (first 14)
        for name, val in zip(FEATURE_NAMES[:14], feats[:14]):
            print(f"{name:<30} | {val:<15.6f}")
            
        # Print first 10 MobileNet embedding values
        for name, val in zip(FEATURE_NAMES[14:24], feats[14:24]):
            print(f"{name:<30} | {val:<15.6f}")
        print(f"{'(... 576 total embedding dims)':<30} | {'...':<15}")
        
        print("-" * 50)
        print(f"Total features extracted: {len(feats)}")
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)
